python src/plot_embeddings.py --gpu 2 --folder lfw --model Facenet
python src/plot_embeddings.py --gpu 2 --folder lfw --model torch_Xu_facenet
python src/plot_embeddings.py --gpu 2 --folder lfw --model vggface2_race_balanced_facenet
python src/plot_embeddings.py --gpu 2 --folder lfw --model vggface2_sex_balanced_facenet
python src/plot_embeddings.py --gpu 2 --folder lfw --model vggface2_default_facenet
python src/plot_embeddings.py --gpu 2 --folder vggface2 --model Facenet
python src/plot_embeddings.py --gpu 2 --folder vggface2 --model torch_Xu_facenet
python src/plot_embeddings.py --gpu 2 --folder vggface2 --model vggface2_race_balanced_facenet
python src/plot_embeddings.py --gpu 2 --folder vggface2 --model vggface2_sex_balanced_facenet
python src/plot_embeddings.py --gpu 2 --folder vggface2 --model vggface2_default_facenet
