python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model torch_Xu_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model torch_Xu_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model torch_Xu_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model torch_Xu_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex

python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model torch_Xu_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex



python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model vggface2_race_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model vggface2_race_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model vggface2_race_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model vggface2_race_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex

python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_race_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex

python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model vggface2_sex_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model vggface2_sex_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model vggface2_sex_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model vggface2_sex_balanced_facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex

python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model vggface2_sex_balanced_facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex




python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Facenet --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model VGG-Face --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model VGG-Face --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model VGG-Face --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model VGG-Face --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model OpenFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model OpenFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model OpenFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model OpenFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepID --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepID --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepID --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model DeepID --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Dlib --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Dlib --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Dlib --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model Dlib --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model ArcFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model ArcFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model ArcFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model ArcFace --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model pytorch --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model pytorch --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model pytorch --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model pytorch --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false

python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model resnet50 --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model resnet50 --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute race --different-flag false
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model resnet50 --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag true
python src/store_embeddings.py --gpu 0 --folder lfw --model Facenet --target-model resnet50 --attack CW --margin 15.0 --amplification 1.0 --granularity no-amp --adversarial-flag true --whitebox-target true --batch-size 20 --attribute sex --different-flag false
